device_actions:
- id: e2e_log_action
  name: Logs a statement to indicate the device action was executed.
  tradefed_target_preparers:
  - class_name: com.android.tradefed.targetprep.RunHostCommandTargetPreparer
    option_values:
    - name: host-setup-command
      values:
      - echo "Executing e2e_log_action on device $SERIAL"

tests:
- id: e2e_fake_test
  name: Custom test suite which executes a fake test.
  command: host --class com.android.tradefed.testtype.FakeTest
